name: racing-weather-api
services:
- name: web
  source_dir: /
  github:
    repo: jaketimm/sports_weather_app_backend
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py main:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: FLASK_ENV
    value: "production"
  - key: PORT
    value: "8080"
  - key: PYTHONPATH
    value: "."
  # Add your other environment variables here
  # - key: YOUR_API_KEY
  #   value: "your-value"
  #   type: SECRET